-- MySQL Script generated by MySQL Workbench
-- Sun Dec 17 21:35:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema consultations
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `consultations` ;

-- -----------------------------------------------------
-- Schema consultations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consultations` DEFAULT CHARACTER SET utf8 ;
USE `consultations` ;

-- -----------------------------------------------------
-- Table `consultations`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`staff` ;

CREATE TABLE IF NOT EXISTS `consultations`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(16) NULL,
  `position` VARCHAR(32) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultations`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`student` ;

CREATE TABLE IF NOT EXISTS `consultations`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(16) NULL,
  `group_name` VARCHAR(8) NULL,
  `graduation_year` YEAR NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultations`.`consultation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`consultation` ;

CREATE TABLE IF NOT EXISTS `consultations`.`consultation` (
  `consultation_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`consultation_id`),
  INDEX `fk_consultation_student_idx` (`student_id` ASC) INVISIBLE,
  INDEX `fk_consultation_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_consultation_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `consultations`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultation_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `consultations`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultations`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`task` ;

CREATE TABLE IF NOT EXISTS `consultations`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `consultation_id` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `body` MEDIUMTEXT NULL,
  `mark` TINYINT NULL,
  PRIMARY KEY (`task_id`, `consultation_id`),
  INDEX `fk_task_consultation1_idx` (`consultation_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_consultation1`
    FOREIGN KEY (`consultation_id`)
    REFERENCES `consultations`.`consultation` (`consultation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultations`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`question` ;

CREATE TABLE IF NOT EXISTS `consultations`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `consultation_id` INT NOT NULL,
  `question` VARCHAR(512) NOT NULL,
  `answer` VARCHAR(512) NULL,
  PRIMARY KEY (`question_id`, `consultation_id`),
  INDEX `fk_question_consultation1_idx` (`consultation_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_consultation1`
    FOREIGN KEY (`consultation_id`)
    REFERENCES `consultations`.`consultation` (`consultation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultations`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultations`.`attachment` ;

CREATE TABLE IF NOT EXISTS `consultations`.`attachment` (
  `attachment_id` INT NOT NULL AUTO_INCREMENT,
  `consultation_id` INT NOT NULL,
  `itle` VARCHAR(64) NOT NULL,
  `body` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`attachment_id`, `consultation_id`),
  INDEX `fk_attachment_consultation1_idx` (`consultation_id` ASC) VISIBLE,
  CONSTRAINT `fk_attachment_consultation1`
    FOREIGN KEY (`consultation_id`)
    REFERENCES `consultations`.`consultation` (`consultation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
